[profile.default]
verbosity = 2
fs_permissions = [{ access = "read", path = "./" }]

## set only when the `hardhat` profile is selected
[profile.hardhat]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]
fs_permissions = [{ access = "read", path = "./" }]


[fuzz]
runs = 1000
seed = '0x1'

[invariant]
runs = 640
depth = 32
fail_on_revert = false
call_override = false
